### ISSUE TITLE
[Epic] Gestion des vétérinaires

### ISSUE THREAD

**Issue by dialsy** [dialsy/testjenkins#1]
<Dans le projet *PetClinic*, il faut ajouter la gestion des vétérinaires.
Implémentation de :
- Création des vétérinaires
- Recherche des vétérinaires
- Mise à jour des vétérinaires
- Suppression des vétérinaires

Tâches à faire :
- [ ] Création des vétérinaires
- [ ] Recherche des vétérinaires
- [ ] Mise à jour des vétérinaires
- [ ] Suppression des vétérinaires
- [ ] Supprimer les vétérinaires
- [ ] Suppression de la base de données>
